# This workflow will install Python dependencies, run tests and lint with a variety of Python versions (currently only Python 3.7)
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
#description: 'Generates pyfalco build, runs tests on push or pull requests of master branch.'
name: 'pyfalco'

on:
  push:
    branches: [ dev-aj]
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # This step checks out a copy of your repository.
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install astropy
        pip install extension-helpers
        mkdir PYPROPER
        cd PYPROPER
        curl https://sourceforge.net/projects/proper-library/files/proper_v3.2.7_python_15jun2022.zip -o myfile.zip -L
        unzip -o myfile.zip
        cd proper*
        python setup.py install
        cd ../../
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov
        pip install pytest-html
        pip install numpy
        pip install scipy
        pip install psutil
        pip install matplotlib
        pip install coveralls
    - name: Test with pytest
      run: |
        #python -m pytest tests/ -v --html=./TestReport/TestReport.html
        python3 -m pytest --cov-report=html  --cov=./falco tests/ -v --html=./TestReport/TestReport.html
#    - name: Upload coverage data to coveralls.io
#      run: coveralls
#      env:
#        GITHUB_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
#    - uses: actions/upload-artifact@v2
#      with:
#        name: my-artifact
#        path: |
#          ./htmlcov/index.html
#          #./TestReport/TestReport.html
